---
language: python
python: 2.7
before_install:
- xport DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- virtualenv buildout --no-setuptools
- source buildout/bin/activate
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg -N -q -t 3
script: bin/test
